version: '3.8'

services:
  build-base-image:
    build:
      context: ./docker/base-image
      dockerfile: Dockerfile
      args:
        CUDA_ARCH: ${CUDA_ARCH:-89-real}
    image: whisperfusion-base:latest
    environment:
      VERBOSE: ${VERBOSE:-true}
    shm_size: 64G
  
  build-models:
    image: whisperfusion-base:latest
    volumes:
      - type: bind
        source: ./docker/scratch-space
        target: /root/scratch-space
    working_dir: /root/scratch-space
    command: ./build-models.sh
    environment:
      VERBOSE: ${VERBOSE:-true}
    shm_size: 64G
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    depends_on:
      - build-base-image
  
  whisperfusion:
    build:
      context: docker
      dockerfile: Dockerfile
    image: whisperfusion:latest
    volumes:
      - type: bind
        source: ./docker/scratch-space
        target: /root/scratch-space
    environment:
      VERBOSE: ${VERBOSE:-false}
    depends_on:
      - build-models
    ports:
      - "8888:8888"
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
  
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/resources/docker/default:/etc/nginx/conf.d/default.conf:ro
      - ./examples/chatbot/html:/var/www/html:ro
    ports:
      - "8000:80"
    depends_on:
      - whisperfusion
    entrypoint: ["/usr/sbin/nginx", "-g", "daemon off;"]
